#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickbeard/.git ]] && \
  git clone --branch coercing-to-Unicode  https://github.com/Mad-Piggy/Sick-Beard.git /app/sickbeard

# permissions
chown -R abc:abc \
	/app
