#!/usr/bin/with-contenv bash

# install app
[[ ! -d /app/sickbeard/.git ]] && \
  git clone --branch dahouet  https://github.com/dahouet/Sick-Beard.git /app/sickbeard

# permissions
chown -R abc:abc \
	/app
